### ISSUE TITLE
Update for WoW Classic

### ISSUE THREAD

**Issue by loser2k1** [Xruptor/RightClickSelfCast#1]
Dear @Xruptor , is it possible to update this addon for WoW Classic?
Many thanks in advance!

**Comment by Xruptor** [comment]
I plan to support both. Problem is I haven't had a chance to return to WOW and update my addons. Also I need to lookup how to migrate addons to Classic. I think it's just a TOC update.

**Comment by Xruptor** [comment]
issue is fixed in commit ef84ffe4340638a5a714c163fe8014a0897e39e3
classic and retail version available.
