### ISSUE TITLE
Update for WotLK

### ISSUE THREAD

**Issue by Nihlo** [Xruptor/RightClickSelfCast#2]
Hey, thanks for the addon. An update to make the addon show up in the wotlk section on curse and removes the toc warning ingame would be cool. Just not 100% sure if a toc change is enough with all those additional bars support.

**Comment by Xruptor** [comment]
Does the addon still work when you click on "Load out of date addons?"  Because if it's a TOC update that isn't hard to do.  Otherwise if it's a bug or it just won't work, then I'd need to investigate.  Please let me know :)

**Comment by Xruptor** [comment]
Haven't heard back in 9 days.  Closing the ticket.

**Comment by Nihlo** [comment]
It's working fine with default Blizz-Bars at least. Besides the old toc obvs.

**Comment by Xruptor** [comment]
> It's working fine with default Blizz-Bars at least. Besides the old toc obvs.

Okay that's good.  I will probably update the TOC files at some point and review the code for the other bar addons.  In general I think ElvUI has an option for it by default not.  So I made just clean up that code.
