### ISSUE TITLE
It just doesn't work

### ISSUE THREAD

**Issue by animaguskitty** [Xruptor/RightClickSelfCast#3]
I've had no issues using this mod for a very long time, but since prepatch, it simply does not function on any of my toons. Right clicking a healing spell while targeting a friendly player uses that spell on the friendly player, not myself. Spells that can't be cast on yourself while targeting an enemy also don't right-click self-cast.

**Comment by Xruptor** [comment]
Do you use any other UI addons?  Like ElvUI, TuiUI, Bartender, etc..?

**Comment by Xruptor** [comment]
Please let me know what other addons you use if any for UI.  I just logged in to Classic, WOTLK and Retail and it works fine.  I used a healer to make things easier.

Targeting a player without RightClickSelfCast enabled and right-clicking a heal causes me to heal the target.  Enabling the addon causes me to heal myself when I right-click and have a player targetted.

This worked fine with the default blizzard UI on all three versions of WOW.

**Comment by Xruptor** [comment]
I haven't heard back in 3 days and I've tested this on multiple characters.  It works just fine with the default Blizzard UI.  Unless you are using another custom interface (ElvUI, TukUI, etc...) it should be working.  Closing this ticket.
