### ISSUE TITLE
Doesnt work :(

### ISSUE THREAD

**Issue by H4X1R** [Xruptor/RightClickSelfCast#6]
Loaded the addon, says up to date. Just doesnt work. Right clicking a healing spell or buff on my druid in Classic wow doesnt do anything.

**Comment by Xruptor** [comment]
Try disabling all addons except RightClickSelfCast on Classic.  See if it works after that.

**Comment by H4X1R** [comment]
ah yeah that works, guess another addon is fighting it. Thanks. Now process of elimination lol

**Comment by Xruptor** [comment]
> ah yeah that works, guess another addon is fighting it. Thanks. Now process of elimination lol

Please let me know which one it is!  That way I can try to debug it myself and perhaps find a solution to it for the future to prevent the conflict.

**Comment by H4X1R** [comment]
It turned out to be Bartender. Apparently it has its own Rclickselfcast function. So i imagine bartender disabled this addon and made it so you had to enable it through that addon.

**Comment by Xruptor** [comment]
> It turned out to be Bartender. Apparently it has its own Rclickselfcast function. So i imagine bartender disabled this addon and made it so you had to enable it through that addon.

OH! Well that totally makes sense since Bartender is a complete Action Bar mod.  So it would definitely overwrite any mods that touch the action bar stuff.  Which includes mine :)  I'm glad you were able to find the issue.
